### ISSUE TITLE
strat_is_valid() should detect the source of a cycle

### ISSUE THREAD

**Issue by tsdye** [joeroe/stratigraphr#3]
igraph has a feedback_arc_set function that can help isolate the source of a cycle.  IIRC, the package implements a fast approximate algorithm (which is helpful) and a slower exact algorithm (which is what most users will probably enjoy).

**Comment by joeroe** [comment]
Thanks, this would indeed be useful. I've been thinking that, in practice, a great deal of the value in Harris matrices comes in the process of finding and correcting relationships that don't make sense. So we probably want to make validity checking as informative and interactive as possible (not just aborting as it does now).

Unfortunately it seems the R interface to igraph doesn't yet implement feedback_arc_set: igraph/rigraph/issues/218. We could look into adding it, or using the C library directly.

**Comment by tsdye** [comment]
Agreed.  An informative error message will be appreciated by users.
